[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
gas_limit = 30000000

# RPC settings for Base mainnet
[rpc_endpoints]
base = "https://mainnet.base.org"

# Etherscan settings for Base
[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Fuzz testing
[fuzz]
runs = 256
max_test_rejects = 65536

# Fork testing - corrected profile notation
[profile.fork]
url = "https://mainnet.base.org"
block_number = 20000000
