// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MyData {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<Event>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(string, tag="1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub contract_address: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub user_address: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub collateral_asset: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub debt_asset: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="7")]
    pub attributes: ::prost::alloc::vec::Vec<Attribute>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attribute {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
